version: "3"
services:

  db:
    image: postgres

  web:
    build: .
    command: python3 manage.py runserver --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "8100:5000"
    links:
      - db